//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCR.Reports.DataModel
{
    using System;
    
    public partial class AssignmentStatusByUser_EPData
    {
        public int SiteID { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> HCOID { get; set; }
        public string Location { get; set; }
        public string Program { get; set; }
        public int ChapterID { get; set; }
        public string Chapter { get; set; }
        public string StandardLabel { get; set; }
        public Nullable<int> EPLabel { get; set; }
        public string ScoreType { get; set; }
        public string ScoreValue { get; set; }
        public string Likelihood { get; set; }
        public string Scope { get; set; }
        public string AssignedBy { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<System.DateTime> ScoreDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int EPTextID { get; set; }
        public string Findings { get; set; }
        public string POA { get; set; }
        public string MOS { get; set; }
        public string OrgNotes { get; set; }
        public string CompliantDate { get; set; }
        public string DocumentList { get; set; }
        public string EPText { get; set; }
        public string ScoredBy { get; set; }
    }
}
