//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCR.Reports.DataModel
{
    using System;
    
    public partial class AssignmentStatusByUser_UserData
    {
        public string AxisKey { get; set; }
        public int SiteID { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> HCOID { get; set; }
        public string Location { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public int ProgramID { get; set; }
        public string Program { get; set; }
        public Nullable<int> EPCount { get; set; }
        public Nullable<int> ScoreCompleteCount { get; set; }
        public Nullable<decimal> ScoreCompletePercentage { get; set; }
        public Nullable<int> ScoreNotCompleteCount { get; set; }
        public Nullable<decimal> ScoreNotCompletePercentage { get; set; }
        public Nullable<int> ScorePastDueDateCount { get; set; }
        public Nullable<decimal> ScorePastDueDatePercentage { get; set; }
        public string SiteFullName { get; set; }
        public string ReportHCOID { get; set; }
    }
}
