//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCR.Reports.DataModel
{
    using System;
    
    public partial class CMSComplianceExcel
    {
        public string Level { get; set; }
        public int CmsStandardID { get; set; }
        public Nullable<int> TagID { get; set; }
        public Nullable<int> CopID { get; set; }
        public Nullable<int> ElementID { get; set; }
        public string TagName { get; set; }
        public string CopStandardName { get; set; }
        public string ConcatenatedText { get; set; }
        public string ComplianceValue { get; set; }
        public string Degree { get; set; }
        public string Manner { get; set; }
        public string DateIdentified { get; set; }
        public string IdentifiedBy { get; set; }
        public string AutoCitationText { get; set; }
        public string OrgCMSFindings { get; set; }
        public string POC { get; set; }
        public string CompliantDate { get; set; }
        public string CSF { get; set; }
        public string LinkedDocumentList { get; set; }
        public Nullable<int> TagSortOrder { get; set; }
        public Nullable<int> CopSortOrder { get; set; }
        public Nullable<int> ElementSortOrder { get; set; }
        public string TJCStandard { get; set; }
        public int SiteID { get; set; }
        public Nullable<int> HCOID { get; set; }
        public string SiteName { get; set; }
        public string ProgramCode { get; set; }
        public string ProgramName { get; set; }
        public string AutoCitationTagText { get; set; }
        public string CopStandard { get; set; }
        public Nullable<int> AutoCitationSortOrder { get; set; }
    }
}
