//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCR.Reports.DataModel
{
    using System;
    
    public partial class CorpEPFinding
    {
        public Nullable<int> HCO_ID { get; set; }
        public string Region_Name { get; set; }
        public string Site_State { get; set; }
        public int SiteID { get; set; }
        public string Hospital_Name { get; set; }
        public string ProgramSettingName { get; set; }
        public string ChapterText { get; set; }
        public string StandardLabel { get; set; }
        public string EPLabel { get; set; }
        public string FSARequired { get; set; }
        public string TJCScore { get; set; }
        public string TJCScoreLikelihood { get; set; }
        public string TJCScoreScope { get; set; }
        public string TJCSurveyDate { get; set; }
        public string TJCFinding { get; set; }
        public string CorpScore { get; set; }
        public string CorpScoreLikelihood { get; set; }
        public string CorpScoreScope { get; set; }
        public string Mock_Survey_Finding { get; set; }
        public string Mock_Survey_Recommendation { get; set; }
        public string MockSurveyDate { get; set; }
        public string MSTeamLead { get; set; }
        public string POA { get; set; }
        public string MOS { get; set; }
        public string ComplaintByDate { get; set; }
        public string MSStatus { get; set; }
        public int ChapterSortOrder { get; set; }
        public short StandardTextSortOrder { get; set; }
        public short SortOrder { get; set; }
    }
}
