//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCR.Reports.DataModel
{
    using System;
    
    public partial class MockSurvey
    {
        public int MockSurveyID { get; set; }
        public string MockSurveyName { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
