//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCR.Reports.CCMService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/JCR.CCM.EmailService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailDetails", Namespace="http://schemas.datacontract.org/2004/07/JCR.CCM.BusinessController")]
    [System.SerializableAttribute()]
    public partial class MailDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmpUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailBCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErUserScheduleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> FailedRecipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] GuidListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TemplateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtNewEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserEmailScheduleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmpUrl {
            get {
                return this.AmpUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.AmpUrlField, value) != true)) {
                    this.AmpUrlField = value;
                    this.RaisePropertyChanged("AmpUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Application {
            get {
                return this.ApplicationField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationField, value) != true)) {
                    this.ApplicationField = value;
                    this.RaisePropertyChanged("Application");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomText {
            get {
                return this.CustomTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomTextField, value) != true)) {
                    this.CustomTextField = value;
                    this.RaisePropertyChanged("CustomText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailBCC {
            get {
                return this.EmailBCCField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailBCCField, value) != true)) {
                    this.EmailBCCField = value;
                    this.RaisePropertyChanged("EmailBCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailCC {
            get {
                return this.EmailCCField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailCCField, value) != true)) {
                    this.EmailCCField = value;
                    this.RaisePropertyChanged("EmailCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailTo {
            get {
                return this.EmailToField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailToField, value) != true)) {
                    this.EmailToField = value;
                    this.RaisePropertyChanged("EmailTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErUserScheduleID {
            get {
                return this.ErUserScheduleIDField;
            }
            set {
                if ((this.ErUserScheduleIDField.Equals(value) != true)) {
                    this.ErUserScheduleIDField = value;
                    this.RaisePropertyChanged("ErUserScheduleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> FailedRecipients {
            get {
                return this.FailedRecipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.FailedRecipientsField, value) != true)) {
                    this.FailedRecipientsField = value;
                    this.RaisePropertyChanged("FailedRecipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromEmail {
            get {
                return this.FromEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.FromEmailField, value) != true)) {
                    this.FromEmailField = value;
                    this.RaisePropertyChanged("FromEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] GuidList {
            get {
                return this.GuidListField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidListField, value) != true)) {
                    this.GuidListField = value;
                    this.RaisePropertyChanged("GuidList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailContent {
            get {
                return this.MailContentField;
            }
            set {
                if ((object.ReferenceEquals(this.MailContentField, value) != true)) {
                    this.MailContentField = value;
                    this.RaisePropertyChanged("MailContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailSubject {
            get {
                return this.MailSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.MailSubjectField, value) != true)) {
                    this.MailSubjectField = value;
                    this.RaisePropertyChanged("MailSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportName {
            get {
                return this.ReportNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportNameField, value) != true)) {
                    this.ReportNameField = value;
                    this.RaisePropertyChanged("ReportName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                if ((this.SiteIDField.Equals(value) != true)) {
                    this.SiteIDField = value;
                    this.RaisePropertyChanged("SiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemplateID {
            get {
                return this.TemplateIDField;
            }
            set {
                if ((this.TemplateIDField.Equals(value) != true)) {
                    this.TemplateIDField = value;
                    this.RaisePropertyChanged("TemplateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtNewEmail {
            get {
                return this.TxtNewEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtNewEmailField, value) != true)) {
                    this.TxtNewEmailField = value;
                    this.RaisePropertyChanged("TxtNewEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserEmailScheduleID {
            get {
                return this.UserEmailScheduleIDField;
            }
            set {
                if ((this.UserEmailScheduleIDField.Equals(value) != true)) {
                    this.UserEmailScheduleIDField = value;
                    this.RaisePropertyChanged("UserEmailScheduleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CCMService.IProcessEmail")]
    public interface IProcessEmail {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/GetData", ReplyAction="http://tempuri.org/IProcessEmail/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/GetData", ReplyAction="http://tempuri.org/IProcessEmail/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IProcessEmail/GetDataUsingDataContractResponse")]
        JCR.Reports.CCMService.CompositeType GetDataUsingDataContract(JCR.Reports.CCMService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IProcessEmail/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<JCR.Reports.CCMService.CompositeType> GetDataUsingDataContractAsync(JCR.Reports.CCMService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendEmailResponse")]
        JCR.Reports.CCMService.SendEmailResponse SendEmail(JCR.Reports.CCMService.SendEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendEmailResponse")]
        System.Threading.Tasks.Task<JCR.Reports.CCMService.SendEmailResponse> SendEmailAsync(JCR.Reports.CCMService.SendEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendEREmail", ReplyAction="http://tempuri.org/IProcessEmail/SendEREmailResponse")]
        JCR.Reports.CCMService.SendEREmailResponse SendEREmail(JCR.Reports.CCMService.SendEREmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendEREmail", ReplyAction="http://tempuri.org/IProcessEmail/SendEREmailResponse")]
        System.Threading.Tasks.Task<JCR.Reports.CCMService.SendEREmailResponse> SendEREmailAsync(JCR.Reports.CCMService.SendEREmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/GetTokenReplacementText", ReplyAction="http://tempuri.org/IProcessEmail/GetTokenReplacementTextResponse")]
        string GetTokenReplacementText(string token, int SiteID, int templateID, bool isBlankOK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/GetTokenReplacementText", ReplyAction="http://tempuri.org/IProcessEmail/GetTokenReplacementTextResponse")]
        System.Threading.Tasks.Task<string> GetTokenReplacementTextAsync(string token, int SiteID, int templateID, bool isBlankOK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendAdhocEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendAdhocEmailResponse")]
        JCR.Reports.CCMService.SendAdhocEmailResponse SendAdhocEmail(JCR.Reports.CCMService.SendAdhocEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendAdhocEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendAdhocEmailResponse")]
        System.Threading.Tasks.Task<JCR.Reports.CCMService.SendAdhocEmailResponse> SendAdhocEmailAsync(JCR.Reports.CCMService.SendAdhocEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/ProcessText", ReplyAction="http://tempuri.org/IProcessEmail/ProcessTextResponse")]
        string ProcessText(int SiteID, int templateID, string templateText, bool isBlankOK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/ProcessText", ReplyAction="http://tempuri.org/IProcessEmail/ProcessTextResponse")]
        System.Threading.Tasks.Task<string> ProcessTextAsync(int SiteID, int templateID, string templateText, bool isBlankOK);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendGeneralEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendGeneralEmailResponse")]
        JCR.Reports.CCMService.SendGeneralEmailResponse SendGeneralEmail(JCR.Reports.CCMService.SendGeneralEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendGeneralEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendGeneralEmailResponse")]
        System.Threading.Tasks.Task<JCR.Reports.CCMService.SendGeneralEmailResponse> SendGeneralEmailAsync(JCR.Reports.CCMService.SendGeneralEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendOversizeEmailAlert", ReplyAction="http://tempuri.org/IProcessEmail/SendOversizeEmailAlertResponse")]
        int SendOversizeEmailAlert(string subject, int siteID, int userID, string reportName, string applicationCode, int actionTypeID, int erReportSchedule, int createdByUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendOversizeEmailAlert", ReplyAction="http://tempuri.org/IProcessEmail/SendOversizeEmailAlertResponse")]
        System.Threading.Tasks.Task<int> SendOversizeEmailAlertAsync(string subject, int siteID, int userID, string reportName, string applicationCode, int actionTypeID, int erReportSchedule, int createdByUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendTracerDeptAssignmentEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendTracerDeptAssignmentEmailResponse")]
        JCR.Reports.CCMService.SendTracerDeptAssignmentEmailResponse SendTracerDeptAssignmentEmail(JCR.Reports.CCMService.SendTracerDeptAssignmentEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessEmail/SendTracerDeptAssignmentEmail", ReplyAction="http://tempuri.org/IProcessEmail/SendTracerDeptAssignmentEmailResponse")]
        System.Threading.Tasks.Task<JCR.Reports.CCMService.SendTracerDeptAssignmentEmailResponse> SendTracerDeptAssignmentEmailAsync(JCR.Reports.CCMService.SendTracerDeptAssignmentEmailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SiteID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int templateID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Collections.Generic.List<string> attachments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string applicationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int actionTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string fnReturnValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int createdByUserId;
        
        public SendEmailRequest() {
        }
        
        public SendEmailRequest(int SiteID, int templateID, System.Collections.Generic.List<string> attachments, string applicationCode, int actionTypeID, string fnReturnValue, int createdByUserId) {
            this.SiteID = SiteID;
            this.templateID = templateID;
            this.attachments = attachments;
            this.applicationCode = applicationCode;
            this.actionTypeID = actionTypeID;
            this.fnReturnValue = fnReturnValue;
            this.createdByUserId = createdByUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fnReturnValue;
        
        public SendEmailResponse() {
        }
        
        public SendEmailResponse(int SendEmailResult, string fnReturnValue) {
            this.SendEmailResult = SendEmailResult;
            this.fnReturnValue = fnReturnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEREmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEREmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ERReportUserScheduleID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int siteID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int templateID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] attachments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string applicationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int actionTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string functionReturnValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int createdByUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string fromEmail;
        
        public SendEREmailRequest() {
        }
        
        public SendEREmailRequest(int ERReportUserScheduleID, int siteID, int templateID, string[] attachments, string applicationCode, int actionTypeID, string functionReturnValue, int createdByUserId, string fromEmail) {
            this.ERReportUserScheduleID = ERReportUserScheduleID;
            this.siteID = siteID;
            this.templateID = templateID;
            this.attachments = attachments;
            this.applicationCode = applicationCode;
            this.actionTypeID = actionTypeID;
            this.functionReturnValue = functionReturnValue;
            this.createdByUserId = createdByUserId;
            this.fromEmail = fromEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEREmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEREmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendEREmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string functionReturnValue;
        
        public SendEREmailResponse() {
        }
        
        public SendEREmailResponse(int SendEREmailResult, string functionReturnValue) {
            this.SendEREmailResult = SendEREmailResult;
            this.functionReturnValue = functionReturnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAdhocEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendAdhocEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SiteID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int templateID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ToEMailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string CCEMailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string applicationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int actionTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string fnReturnValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int createdByUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string txtEmailSubject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string txtNewEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public System.Collections.Generic.List<string> attachments;
        
        public SendAdhocEmailRequest() {
        }
        
        public SendAdhocEmailRequest(int SiteID, int templateID, string ToEMailAddress, string CCEMailAddress, string applicationCode, int actionTypeID, string fnReturnValue, int createdByUserId, string txtEmailSubject, string txtNewEmail, System.Collections.Generic.List<string> attachments) {
            this.SiteID = SiteID;
            this.templateID = templateID;
            this.ToEMailAddress = ToEMailAddress;
            this.CCEMailAddress = CCEMailAddress;
            this.applicationCode = applicationCode;
            this.actionTypeID = actionTypeID;
            this.fnReturnValue = fnReturnValue;
            this.createdByUserId = createdByUserId;
            this.txtEmailSubject = txtEmailSubject;
            this.txtNewEmail = txtNewEmail;
            this.attachments = attachments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAdhocEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendAdhocEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendAdhocEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fnReturnValue;
        
        public SendAdhocEmailResponse() {
        }
        
        public SendAdhocEmailResponse(int SendAdhocEmailResult, string fnReturnValue) {
            this.SendAdhocEmailResult = SendAdhocEmailResult;
            this.fnReturnValue = fnReturnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendGeneralEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendGeneralEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public JCR.Reports.CCMService.MailDetails mailDetails;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fnReturnValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string applicationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int actionTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int createdByUserId;
        
        public SendGeneralEmailRequest() {
        }
        
        public SendGeneralEmailRequest(JCR.Reports.CCMService.MailDetails mailDetails, string fnReturnValue, string applicationCode, int actionTypeID, int createdByUserId) {
            this.mailDetails = mailDetails;
            this.fnReturnValue = fnReturnValue;
            this.applicationCode = applicationCode;
            this.actionTypeID = actionTypeID;
            this.createdByUserId = createdByUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendGeneralEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendGeneralEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendGeneralEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fnReturnValue;
        
        public SendGeneralEmailResponse() {
        }
        
        public SendGeneralEmailResponse(int SendGeneralEmailResult, string fnReturnValue) {
            this.SendGeneralEmailResult = SendGeneralEmailResult;
            this.fnReturnValue = fnReturnValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendTracerDeptAssignmentEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendTracerDeptAssignmentEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int siteID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int userEmailScheduleID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int templateID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Collections.Generic.List<string> attachments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string applicationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int actionTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string functionReturnValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int createdByUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string fromEmail;
        
        public SendTracerDeptAssignmentEmailRequest() {
        }
        
        public SendTracerDeptAssignmentEmailRequest(int siteID, int userEmailScheduleID, int templateID, System.Collections.Generic.List<string> attachments, string applicationCode, int actionTypeID, string functionReturnValue, int createdByUserId, string fromEmail) {
            this.siteID = siteID;
            this.userEmailScheduleID = userEmailScheduleID;
            this.templateID = templateID;
            this.attachments = attachments;
            this.applicationCode = applicationCode;
            this.actionTypeID = actionTypeID;
            this.functionReturnValue = functionReturnValue;
            this.createdByUserId = createdByUserId;
            this.fromEmail = fromEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendTracerDeptAssignmentEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendTracerDeptAssignmentEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendTracerDeptAssignmentEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string functionReturnValue;
        
        public SendTracerDeptAssignmentEmailResponse() {
        }
        
        public SendTracerDeptAssignmentEmailResponse(int SendTracerDeptAssignmentEmailResult, string functionReturnValue) {
            this.SendTracerDeptAssignmentEmailResult = SendTracerDeptAssignmentEmailResult;
            this.functionReturnValue = functionReturnValue;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProcessEmailChannel : JCR.Reports.CCMService.IProcessEmail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessEmailClient : System.ServiceModel.ClientBase<JCR.Reports.CCMService.IProcessEmail>, JCR.Reports.CCMService.IProcessEmail {
        
        public ProcessEmailClient() {
        }
        
        public ProcessEmailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessEmailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessEmailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessEmailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public JCR.Reports.CCMService.CompositeType GetDataUsingDataContract(JCR.Reports.CCMService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<JCR.Reports.CCMService.CompositeType> GetDataUsingDataContractAsync(JCR.Reports.CCMService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JCR.Reports.CCMService.SendEmailResponse JCR.Reports.CCMService.IProcessEmail.SendEmail(JCR.Reports.CCMService.SendEmailRequest request) {
            return base.Channel.SendEmail(request);
        }
        
        public int SendEmail(int SiteID, int templateID, System.Collections.Generic.List<string> attachments, string applicationCode, int actionTypeID, ref string fnReturnValue, int createdByUserId) {
            JCR.Reports.CCMService.SendEmailRequest inValue = new JCR.Reports.CCMService.SendEmailRequest();
            inValue.SiteID = SiteID;
            inValue.templateID = templateID;
            inValue.attachments = attachments;
            inValue.applicationCode = applicationCode;
            inValue.actionTypeID = actionTypeID;
            inValue.fnReturnValue = fnReturnValue;
            inValue.createdByUserId = createdByUserId;
            JCR.Reports.CCMService.SendEmailResponse retVal = ((JCR.Reports.CCMService.IProcessEmail)(this)).SendEmail(inValue);
            fnReturnValue = retVal.fnReturnValue;
            return retVal.SendEmailResult;
        }
        
        public System.Threading.Tasks.Task<JCR.Reports.CCMService.SendEmailResponse> SendEmailAsync(JCR.Reports.CCMService.SendEmailRequest request) {
            return base.Channel.SendEmailAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JCR.Reports.CCMService.SendEREmailResponse JCR.Reports.CCMService.IProcessEmail.SendEREmail(JCR.Reports.CCMService.SendEREmailRequest request) {
            return base.Channel.SendEREmail(request);
        }
        
        public int SendEREmail(int ERReportUserScheduleID, int siteID, int templateID, string[] attachments, string applicationCode, int actionTypeID, ref string functionReturnValue, int createdByUserId, string fromEmail) {
            JCR.Reports.CCMService.SendEREmailRequest inValue = new JCR.Reports.CCMService.SendEREmailRequest();
            inValue.ERReportUserScheduleID = ERReportUserScheduleID;
            inValue.siteID = siteID;
            inValue.templateID = templateID;
            inValue.attachments = attachments;
            inValue.applicationCode = applicationCode;
            inValue.actionTypeID = actionTypeID;
            inValue.functionReturnValue = functionReturnValue;
            inValue.createdByUserId = createdByUserId;
            inValue.fromEmail = fromEmail;
            JCR.Reports.CCMService.SendEREmailResponse retVal = ((JCR.Reports.CCMService.IProcessEmail)(this)).SendEREmail(inValue);
            functionReturnValue = retVal.functionReturnValue;
            return retVal.SendEREmailResult;
        }
        
        public System.Threading.Tasks.Task<JCR.Reports.CCMService.SendEREmailResponse> SendEREmailAsync(JCR.Reports.CCMService.SendEREmailRequest request) {
            return base.Channel.SendEREmailAsync(request);
        }
        
        public string GetTokenReplacementText(string token, int SiteID, int templateID, bool isBlankOK) {
            return base.Channel.GetTokenReplacementText(token, SiteID, templateID, isBlankOK);
        }
        
        public System.Threading.Tasks.Task<string> GetTokenReplacementTextAsync(string token, int SiteID, int templateID, bool isBlankOK) {
            return base.Channel.GetTokenReplacementTextAsync(token, SiteID, templateID, isBlankOK);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JCR.Reports.CCMService.SendAdhocEmailResponse JCR.Reports.CCMService.IProcessEmail.SendAdhocEmail(JCR.Reports.CCMService.SendAdhocEmailRequest request) {
            return base.Channel.SendAdhocEmail(request);
        }
        
        public int SendAdhocEmail(int SiteID, int templateID, string ToEMailAddress, string CCEMailAddress, string applicationCode, int actionTypeID, ref string fnReturnValue, int createdByUserId, string txtEmailSubject, string txtNewEmail, System.Collections.Generic.List<string> attachments) {
            JCR.Reports.CCMService.SendAdhocEmailRequest inValue = new JCR.Reports.CCMService.SendAdhocEmailRequest();
            inValue.SiteID = SiteID;
            inValue.templateID = templateID;
            inValue.ToEMailAddress = ToEMailAddress;
            inValue.CCEMailAddress = CCEMailAddress;
            inValue.applicationCode = applicationCode;
            inValue.actionTypeID = actionTypeID;
            inValue.fnReturnValue = fnReturnValue;
            inValue.createdByUserId = createdByUserId;
            inValue.txtEmailSubject = txtEmailSubject;
            inValue.txtNewEmail = txtNewEmail;
            inValue.attachments = attachments;
            JCR.Reports.CCMService.SendAdhocEmailResponse retVal = ((JCR.Reports.CCMService.IProcessEmail)(this)).SendAdhocEmail(inValue);
            fnReturnValue = retVal.fnReturnValue;
            return retVal.SendAdhocEmailResult;
        }
        
        public System.Threading.Tasks.Task<JCR.Reports.CCMService.SendAdhocEmailResponse> SendAdhocEmailAsync(JCR.Reports.CCMService.SendAdhocEmailRequest request) {
            return base.Channel.SendAdhocEmailAsync(request);
        }
        
        public string ProcessText(int SiteID, int templateID, string templateText, bool isBlankOK) {
            return base.Channel.ProcessText(SiteID, templateID, templateText, isBlankOK);
        }
        
        public System.Threading.Tasks.Task<string> ProcessTextAsync(int SiteID, int templateID, string templateText, bool isBlankOK) {
            return base.Channel.ProcessTextAsync(SiteID, templateID, templateText, isBlankOK);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JCR.Reports.CCMService.SendGeneralEmailResponse JCR.Reports.CCMService.IProcessEmail.SendGeneralEmail(JCR.Reports.CCMService.SendGeneralEmailRequest request) {
            return base.Channel.SendGeneralEmail(request);
        }
        
        public int SendGeneralEmail(JCR.Reports.CCMService.MailDetails mailDetails, ref string fnReturnValue, string applicationCode, int actionTypeID, int createdByUserId) {
            JCR.Reports.CCMService.SendGeneralEmailRequest inValue = new JCR.Reports.CCMService.SendGeneralEmailRequest();
            inValue.mailDetails = mailDetails;
            inValue.fnReturnValue = fnReturnValue;
            inValue.applicationCode = applicationCode;
            inValue.actionTypeID = actionTypeID;
            inValue.createdByUserId = createdByUserId;
            JCR.Reports.CCMService.SendGeneralEmailResponse retVal = ((JCR.Reports.CCMService.IProcessEmail)(this)).SendGeneralEmail(inValue);
            fnReturnValue = retVal.fnReturnValue;
            return retVal.SendGeneralEmailResult;
        }
        
        public System.Threading.Tasks.Task<JCR.Reports.CCMService.SendGeneralEmailResponse> SendGeneralEmailAsync(JCR.Reports.CCMService.SendGeneralEmailRequest request) {
            return base.Channel.SendGeneralEmailAsync(request);
        }
        
        public int SendOversizeEmailAlert(string subject, int siteID, int userID, string reportName, string applicationCode, int actionTypeID, int erReportSchedule, int createdByUserId) {
            return base.Channel.SendOversizeEmailAlert(subject, siteID, userID, reportName, applicationCode, actionTypeID, erReportSchedule, createdByUserId);
        }
        
        public System.Threading.Tasks.Task<int> SendOversizeEmailAlertAsync(string subject, int siteID, int userID, string reportName, string applicationCode, int actionTypeID, int erReportSchedule, int createdByUserId) {
            return base.Channel.SendOversizeEmailAlertAsync(subject, siteID, userID, reportName, applicationCode, actionTypeID, erReportSchedule, createdByUserId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JCR.Reports.CCMService.SendTracerDeptAssignmentEmailResponse JCR.Reports.CCMService.IProcessEmail.SendTracerDeptAssignmentEmail(JCR.Reports.CCMService.SendTracerDeptAssignmentEmailRequest request) {
            return base.Channel.SendTracerDeptAssignmentEmail(request);
        }
        
        public int SendTracerDeptAssignmentEmail(int siteID, int userEmailScheduleID, int templateID, System.Collections.Generic.List<string> attachments, string applicationCode, int actionTypeID, ref string functionReturnValue, int createdByUserId, string fromEmail) {
            JCR.Reports.CCMService.SendTracerDeptAssignmentEmailRequest inValue = new JCR.Reports.CCMService.SendTracerDeptAssignmentEmailRequest();
            inValue.siteID = siteID;
            inValue.userEmailScheduleID = userEmailScheduleID;
            inValue.templateID = templateID;
            inValue.attachments = attachments;
            inValue.applicationCode = applicationCode;
            inValue.actionTypeID = actionTypeID;
            inValue.functionReturnValue = functionReturnValue;
            inValue.createdByUserId = createdByUserId;
            inValue.fromEmail = fromEmail;
            JCR.Reports.CCMService.SendTracerDeptAssignmentEmailResponse retVal = ((JCR.Reports.CCMService.IProcessEmail)(this)).SendTracerDeptAssignmentEmail(inValue);
            functionReturnValue = retVal.functionReturnValue;
            return retVal.SendTracerDeptAssignmentEmailResult;
        }
        
        public System.Threading.Tasks.Task<JCR.Reports.CCMService.SendTracerDeptAssignmentEmailResponse> SendTracerDeptAssignmentEmailAsync(JCR.Reports.CCMService.SendTracerDeptAssignmentEmailRequest request) {
            return base.Channel.SendTracerDeptAssignmentEmailAsync(request);
        }
    }
}
