//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace JCR.Reports.App_Data {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsReport_TracerComplianceSummaryByQuestion")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsReport_TracerComplianceSummaryByQuestion : global::System.Data.DataSet {
        
        private dsReport_TracerComplianceSummaryByQuestionDataTable tabledsReport_TracerComplianceSummaryByQuestion;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public dsReport_TracerComplianceSummaryByQuestion() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected dsReport_TracerComplianceSummaryByQuestion(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dsReport_TracerComplianceSummaryByQuestion"] != null)) {
                    base.Tables.Add(new dsReport_TracerComplianceSummaryByQuestionDataTable(ds.Tables["dsReport_TracerComplianceSummaryByQuestion"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dsReport_TracerComplianceSummaryByQuestionDataTable _dsReport_TracerComplianceSummaryByQuestion {
            get {
                return this.tabledsReport_TracerComplianceSummaryByQuestion;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsReport_TracerComplianceSummaryByQuestion cln = ((dsReport_TracerComplianceSummaryByQuestion)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dsReport_TracerComplianceSummaryByQuestion"] != null)) {
                    base.Tables.Add(new dsReport_TracerComplianceSummaryByQuestionDataTable(ds.Tables["dsReport_TracerComplianceSummaryByQuestion"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabledsReport_TracerComplianceSummaryByQuestion = ((dsReport_TracerComplianceSummaryByQuestionDataTable)(base.Tables["dsReport_TracerComplianceSummaryByQuestion"]));
            if ((initTable == true)) {
                if ((this.tabledsReport_TracerComplianceSummaryByQuestion != null)) {
                    this.tabledsReport_TracerComplianceSummaryByQuestion.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsReport_TracerComplianceSummaryByQuestion";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsReport_TracerComplianceSummaryByQuestion.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledsReport_TracerComplianceSummaryByQuestion = new dsReport_TracerComplianceSummaryByQuestionDataTable();
            base.Tables.Add(this.tabledsReport_TracerComplianceSummaryByQuestion);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerialize_dsReport_TracerComplianceSummaryByQuestion() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsReport_TracerComplianceSummaryByQuestion ds = new dsReport_TracerComplianceSummaryByQuestion();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void dsReport_TracerComplianceSummaryByQuestionRowChangeEventHandler(object sender, dsReport_TracerComplianceSummaryByQuestionRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dsReport_TracerComplianceSummaryByQuestionDataTable : global::System.Data.TypedTableBase<dsReport_TracerComplianceSummaryByQuestionRow> {
            
            private global::System.Data.DataColumn columnTracerCustomID;
            
            private global::System.Data.DataColumn columnTracerCustomName;
            
            private global::System.Data.DataColumn columnQuestionNo;
            
            private global::System.Data.DataColumn columnTracerQuestionID;
            
            private global::System.Data.DataColumn columnQuestionText;
            
            private global::System.Data.DataColumn columnObservationCount;
            
            private global::System.Data.DataColumn columnQuestionCount;
            
            private global::System.Data.DataColumn columnNACount;
            
            private global::System.Data.DataColumn columnNumerator;
            
            private global::System.Data.DataColumn columnDenominator;
            
            private global::System.Data.DataColumn columnCompliancePercent;
            
            private global::System.Data.DataColumn columnNonCompliancePercent;
            
            private global::System.Data.DataColumn columnPageGroup;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsReport_TracerComplianceSummaryByQuestionDataTable() {
                this.TableName = "dsReport_TracerComplianceSummaryByQuestion";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dsReport_TracerComplianceSummaryByQuestionDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected dsReport_TracerComplianceSummaryByQuestionDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TracerCustomIDColumn {
                get {
                    return this.columnTracerCustomID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TracerCustomNameColumn {
                get {
                    return this.columnTracerCustomName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QuestionNoColumn {
                get {
                    return this.columnQuestionNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TracerQuestionIDColumn {
                get {
                    return this.columnTracerQuestionID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QuestionTextColumn {
                get {
                    return this.columnQuestionText;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ObservationCountColumn {
                get {
                    return this.columnObservationCount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QuestionCountColumn {
                get {
                    return this.columnQuestionCount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NACountColumn {
                get {
                    return this.columnNACount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NumeratorColumn {
                get {
                    return this.columnNumerator;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DenominatorColumn {
                get {
                    return this.columnDenominator;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CompliancePercentColumn {
                get {
                    return this.columnCompliancePercent;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NonCompliancePercentColumn {
                get {
                    return this.columnNonCompliancePercent;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PageGroupColumn {
                get {
                    return this.columnPageGroup;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsReport_TracerComplianceSummaryByQuestionRow this[int index] {
                get {
                    return ((dsReport_TracerComplianceSummaryByQuestionRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsReport_TracerComplianceSummaryByQuestionRowChangeEventHandler dsReport_TracerComplianceSummaryByQuestionRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsReport_TracerComplianceSummaryByQuestionRowChangeEventHandler dsReport_TracerComplianceSummaryByQuestionRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsReport_TracerComplianceSummaryByQuestionRowChangeEventHandler dsReport_TracerComplianceSummaryByQuestionRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsReport_TracerComplianceSummaryByQuestionRowChangeEventHandler dsReport_TracerComplianceSummaryByQuestionRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AdddsReport_TracerComplianceSummaryByQuestionRow(dsReport_TracerComplianceSummaryByQuestionRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsReport_TracerComplianceSummaryByQuestionRow AdddsReport_TracerComplianceSummaryByQuestionRow(int TracerCustomID, string TracerCustomName, int QuestionNo, int TracerQuestionID, string QuestionText, int ObservationCount, int QuestionCount, int NACount, decimal Numerator, decimal Denominator, decimal CompliancePercent, decimal NonCompliancePercent, int PageGroup) {
                dsReport_TracerComplianceSummaryByQuestionRow rowdsReport_TracerComplianceSummaryByQuestionRow = ((dsReport_TracerComplianceSummaryByQuestionRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        TracerCustomID,
                        TracerCustomName,
                        QuestionNo,
                        TracerQuestionID,
                        QuestionText,
                        ObservationCount,
                        QuestionCount,
                        NACount,
                        Numerator,
                        Denominator,
                        CompliancePercent,
                        NonCompliancePercent,
                        PageGroup};
                rowdsReport_TracerComplianceSummaryByQuestionRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdsReport_TracerComplianceSummaryByQuestionRow);
                return rowdsReport_TracerComplianceSummaryByQuestionRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dsReport_TracerComplianceSummaryByQuestionDataTable cln = ((dsReport_TracerComplianceSummaryByQuestionDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dsReport_TracerComplianceSummaryByQuestionDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnTracerCustomID = base.Columns["TracerCustomID"];
                this.columnTracerCustomName = base.Columns["TracerCustomName"];
                this.columnQuestionNo = base.Columns["QuestionNo"];
                this.columnTracerQuestionID = base.Columns["TracerQuestionID"];
                this.columnQuestionText = base.Columns["QuestionText"];
                this.columnObservationCount = base.Columns["ObservationCount"];
                this.columnQuestionCount = base.Columns["QuestionCount"];
                this.columnNACount = base.Columns["NACount"];
                this.columnNumerator = base.Columns["Numerator"];
                this.columnDenominator = base.Columns["Denominator"];
                this.columnCompliancePercent = base.Columns["CompliancePercent"];
                this.columnNonCompliancePercent = base.Columns["NonCompliancePercent"];
                this.columnPageGroup = base.Columns["PageGroup"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnTracerCustomID = new global::System.Data.DataColumn("TracerCustomID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTracerCustomID);
                this.columnTracerCustomName = new global::System.Data.DataColumn("TracerCustomName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTracerCustomName);
                this.columnQuestionNo = new global::System.Data.DataColumn("QuestionNo", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQuestionNo);
                this.columnTracerQuestionID = new global::System.Data.DataColumn("TracerQuestionID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTracerQuestionID);
                this.columnQuestionText = new global::System.Data.DataColumn("QuestionText", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQuestionText);
                this.columnObservationCount = new global::System.Data.DataColumn("ObservationCount", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnObservationCount);
                this.columnQuestionCount = new global::System.Data.DataColumn("QuestionCount", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQuestionCount);
                this.columnNACount = new global::System.Data.DataColumn("NACount", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNACount);
                this.columnNumerator = new global::System.Data.DataColumn("Numerator", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNumerator);
                this.columnDenominator = new global::System.Data.DataColumn("Denominator", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDenominator);
                this.columnCompliancePercent = new global::System.Data.DataColumn("CompliancePercent", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCompliancePercent);
                this.columnNonCompliancePercent = new global::System.Data.DataColumn("NonCompliancePercent", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNonCompliancePercent);
                this.columnPageGroup = new global::System.Data.DataColumn("PageGroup", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPageGroup);
                this.columnPageGroup.DefaultValue = ((int)(1));
                this.ExtendedProperties.Add("Generator_TablePropName", "_dsReport_TracerComplianceSummaryByQuestion");
                this.ExtendedProperties.Add("Generator_UserTableName", "dsReport_TracerComplianceSummaryByQuestion");
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsReport_TracerComplianceSummaryByQuestionRow NewdsReport_TracerComplianceSummaryByQuestionRow() {
                return ((dsReport_TracerComplianceSummaryByQuestionRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dsReport_TracerComplianceSummaryByQuestionRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dsReport_TracerComplianceSummaryByQuestionRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dsReport_TracerComplianceSummaryByQuestionRowChanged != null)) {
                    this.dsReport_TracerComplianceSummaryByQuestionRowChanged(this, new dsReport_TracerComplianceSummaryByQuestionRowChangeEvent(((dsReport_TracerComplianceSummaryByQuestionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dsReport_TracerComplianceSummaryByQuestionRowChanging != null)) {
                    this.dsReport_TracerComplianceSummaryByQuestionRowChanging(this, new dsReport_TracerComplianceSummaryByQuestionRowChangeEvent(((dsReport_TracerComplianceSummaryByQuestionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dsReport_TracerComplianceSummaryByQuestionRowDeleted != null)) {
                    this.dsReport_TracerComplianceSummaryByQuestionRowDeleted(this, new dsReport_TracerComplianceSummaryByQuestionRowChangeEvent(((dsReport_TracerComplianceSummaryByQuestionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dsReport_TracerComplianceSummaryByQuestionRowDeleting != null)) {
                    this.dsReport_TracerComplianceSummaryByQuestionRowDeleting(this, new dsReport_TracerComplianceSummaryByQuestionRowChangeEvent(((dsReport_TracerComplianceSummaryByQuestionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemovedsReport_TracerComplianceSummaryByQuestionRow(dsReport_TracerComplianceSummaryByQuestionRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsReport_TracerComplianceSummaryByQuestion ds = new dsReport_TracerComplianceSummaryByQuestion();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dsReport_TracerComplianceSummaryByQuestionDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dsReport_TracerComplianceSummaryByQuestionRow : global::System.Data.DataRow {
            
            private dsReport_TracerComplianceSummaryByQuestionDataTable tabledsReport_TracerComplianceSummaryByQuestion;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dsReport_TracerComplianceSummaryByQuestionRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledsReport_TracerComplianceSummaryByQuestion = ((dsReport_TracerComplianceSummaryByQuestionDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int TracerCustomID {
                get {
                    try {
                        return ((int)(this[this.tabledsReport_TracerComplianceSummaryByQuestion.TracerCustomIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TracerCustomID\' in table \'dsReport_TracerComplianceSummaryB" +
                                "yQuestion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsReport_TracerComplianceSummaryByQuestion.TracerCustomIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string TracerCustomName {
                get {
                    try {
                        return ((string)(this[this.tabledsReport_TracerComplianceSummaryByQuestion.TracerCustomNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TracerCustomName\' in table \'dsReport_TracerComplianceSummar" +
                                "yByQuestion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsReport_TracerComplianceSummaryByQuestion.TracerCustomNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int QuestionNo {
                get {
                    try {
                        return ((int)(this[this.tabledsReport_TracerComplianceSummaryByQuestion.QuestionNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'QuestionNo\' in table \'dsReport_TracerComplianceSummaryByQue" +
                                "stion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsReport_TracerComplianceSummaryByQuestion.QuestionNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int TracerQuestionID {
                get {
                    try {
                        return ((int)(this[this.tabledsReport_TracerComplianceSummaryByQuestion.TracerQuestionIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TracerQuestionID\' in table \'dsReport_TracerComplianceSummar" +
                                "yByQuestion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsReport_TracerComplianceSummaryByQuestion.TracerQuestionIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string QuestionText {
                get {
                    try {
                        return ((string)(this[this.tabledsReport_TracerComplianceSummaryByQuestion.QuestionTextColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'QuestionText\' in table \'dsReport_TracerComplianceSummaryByQ" +
                                "uestion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsReport_TracerComplianceSummaryByQuestion.QuestionTextColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int ObservationCount {
                get {
                    try {
                        return ((int)(this[this.tabledsReport_TracerComplianceSummaryByQuestion.ObservationCountColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ObservationCount\' in table \'dsReport_TracerComplianceSummar" +
                                "yByQuestion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsReport_TracerComplianceSummaryByQuestion.ObservationCountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int QuestionCount {
                get {
                    try {
                        return ((int)(this[this.tabledsReport_TracerComplianceSummaryByQuestion.QuestionCountColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'QuestionCount\' in table \'dsReport_TracerComplianceSummaryBy" +
                                "Question\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsReport_TracerComplianceSummaryByQuestion.QuestionCountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int NACount {
                get {
                    try {
                        return ((int)(this[this.tabledsReport_TracerComplianceSummaryByQuestion.NACountColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NACount\' in table \'dsReport_TracerComplianceSummaryByQuesti" +
                                "on\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsReport_TracerComplianceSummaryByQuestion.NACountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal Numerator {
                get {
                    try {
                        return ((decimal)(this[this.tabledsReport_TracerComplianceSummaryByQuestion.NumeratorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Numerator\' in table \'dsReport_TracerComplianceSummaryByQues" +
                                "tion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsReport_TracerComplianceSummaryByQuestion.NumeratorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal Denominator {
                get {
                    try {
                        return ((decimal)(this[this.tabledsReport_TracerComplianceSummaryByQuestion.DenominatorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Denominator\' in table \'dsReport_TracerComplianceSummaryByQu" +
                                "estion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsReport_TracerComplianceSummaryByQuestion.DenominatorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal CompliancePercent {
                get {
                    try {
                        return ((decimal)(this[this.tabledsReport_TracerComplianceSummaryByQuestion.CompliancePercentColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CompliancePercent\' in table \'dsReport_TracerComplianceSumma" +
                                "ryByQuestion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsReport_TracerComplianceSummaryByQuestion.CompliancePercentColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal NonCompliancePercent {
                get {
                    try {
                        return ((decimal)(this[this.tabledsReport_TracerComplianceSummaryByQuestion.NonCompliancePercentColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NonCompliancePercent\' in table \'dsReport_TracerComplianceSu" +
                                "mmaryByQuestion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsReport_TracerComplianceSummaryByQuestion.NonCompliancePercentColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int PageGroup {
                get {
                    try {
                        return ((int)(this[this.tabledsReport_TracerComplianceSummaryByQuestion.PageGroupColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PageGroup\' in table \'dsReport_TracerComplianceSummaryByQues" +
                                "tion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsReport_TracerComplianceSummaryByQuestion.PageGroupColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTracerCustomIDNull() {
                return this.IsNull(this.tabledsReport_TracerComplianceSummaryByQuestion.TracerCustomIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTracerCustomIDNull() {
                this[this.tabledsReport_TracerComplianceSummaryByQuestion.TracerCustomIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTracerCustomNameNull() {
                return this.IsNull(this.tabledsReport_TracerComplianceSummaryByQuestion.TracerCustomNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTracerCustomNameNull() {
                this[this.tabledsReport_TracerComplianceSummaryByQuestion.TracerCustomNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQuestionNoNull() {
                return this.IsNull(this.tabledsReport_TracerComplianceSummaryByQuestion.QuestionNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQuestionNoNull() {
                this[this.tabledsReport_TracerComplianceSummaryByQuestion.QuestionNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTracerQuestionIDNull() {
                return this.IsNull(this.tabledsReport_TracerComplianceSummaryByQuestion.TracerQuestionIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTracerQuestionIDNull() {
                this[this.tabledsReport_TracerComplianceSummaryByQuestion.TracerQuestionIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQuestionTextNull() {
                return this.IsNull(this.tabledsReport_TracerComplianceSummaryByQuestion.QuestionTextColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQuestionTextNull() {
                this[this.tabledsReport_TracerComplianceSummaryByQuestion.QuestionTextColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsObservationCountNull() {
                return this.IsNull(this.tabledsReport_TracerComplianceSummaryByQuestion.ObservationCountColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetObservationCountNull() {
                this[this.tabledsReport_TracerComplianceSummaryByQuestion.ObservationCountColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQuestionCountNull() {
                return this.IsNull(this.tabledsReport_TracerComplianceSummaryByQuestion.QuestionCountColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQuestionCountNull() {
                this[this.tabledsReport_TracerComplianceSummaryByQuestion.QuestionCountColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNACountNull() {
                return this.IsNull(this.tabledsReport_TracerComplianceSummaryByQuestion.NACountColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNACountNull() {
                this[this.tabledsReport_TracerComplianceSummaryByQuestion.NACountColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNumeratorNull() {
                return this.IsNull(this.tabledsReport_TracerComplianceSummaryByQuestion.NumeratorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNumeratorNull() {
                this[this.tabledsReport_TracerComplianceSummaryByQuestion.NumeratorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDenominatorNull() {
                return this.IsNull(this.tabledsReport_TracerComplianceSummaryByQuestion.DenominatorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDenominatorNull() {
                this[this.tabledsReport_TracerComplianceSummaryByQuestion.DenominatorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCompliancePercentNull() {
                return this.IsNull(this.tabledsReport_TracerComplianceSummaryByQuestion.CompliancePercentColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCompliancePercentNull() {
                this[this.tabledsReport_TracerComplianceSummaryByQuestion.CompliancePercentColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNonCompliancePercentNull() {
                return this.IsNull(this.tabledsReport_TracerComplianceSummaryByQuestion.NonCompliancePercentColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNonCompliancePercentNull() {
                this[this.tabledsReport_TracerComplianceSummaryByQuestion.NonCompliancePercentColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPageGroupNull() {
                return this.IsNull(this.tabledsReport_TracerComplianceSummaryByQuestion.PageGroupColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPageGroupNull() {
                this[this.tabledsReport_TracerComplianceSummaryByQuestion.PageGroupColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class dsReport_TracerComplianceSummaryByQuestionRowChangeEvent : global::System.EventArgs {
            
            private dsReport_TracerComplianceSummaryByQuestionRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsReport_TracerComplianceSummaryByQuestionRowChangeEvent(dsReport_TracerComplianceSummaryByQuestionRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsReport_TracerComplianceSummaryByQuestionRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591